
import { Inter } from "next/font/google";
import "@/globals.css";
import Sidebar from "./components/organisms/Sidebar";
import { sidebarInfo } from "@/app/data/sidebarInfo";
import AOSInit from "@/app/hooks/AOSInit";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#040604] ${inter.className} antialiased`}>
        <AOSInit />
        {/* Sidebar */}
        <aside className="sidebar">
          {sidebarInfo.map((i) => (
            <Sidebar key={i.id} {...i} />
          ))}
        </aside>

        <main className="bg-[#060906] pb-20 md:pb-0 md:pl-20 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}